apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  selector:
    matchLabels:
      app: app-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: app-deployment
    spec:
      containers:
      - name: bank-end
        image: __DOCKER_REPOSITORY__/__IMAGE_NAME__BE:__IMAGE_TAG__
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 300m
            memory: "100Mi"
          requests:
            cpu: 100m
            memory: "50Mi"
      - name: backend
        image: __DOCKER_REPOSITORY__/__IMAGE_NAME__FE:__IMAGE_TAG__
        resources:
          limits:
            cpu: 300m
            memory: "100Mi"
          requests:
            cpu: 100m
            memory: "50Mi"
        # env:
        #   - name: ConnectionStrings__ProductsContext
        #     valueFrom:
        #       configMapKeyRef:
        #         name: mssql-connection-configmap
        #         key: db-connection-string
        #     secretKeyRef:
        #       name: mssql-secret
        #       key: db-connection-string-secret
---
kind: Service
apiVersion: v1
metadata:
  name: front-end-service
spec:
  selector:
    app: front-end
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer #NodePort