apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-end-deployment
spec:
  selector:
    matchLabels:
      app: back-end
  replicas: 1
  template:
    metadata:
      labels:
        app: back-end
    spec:
      containers:
      - name: back-end
        image: __DOCKER_REPOSITORY__/__IMAGE_NAME_BE__:__IMAGE_TAG__
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 2800m
            memory: "4000Mi"
          requests:
            cpu: 100m
            memory: "50Mi"
        # env:
        #   - name: ConnectionStrings__ProductsContext
        #     valueFrom:
        #       configMapKeyRef:
        #         name: mssql-connection-configmap
        #         key: db-connection-string
        #     secretKeyRef:
        #       name: mssql-secret
        #       key: db-connection-string-secret
---
kind: Service
apiVersion: v1
metadata:
  name: back-end-service
spec:
  selector:
    app: back-end
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer #NodePort