apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end-deployment
spec:
  selector:
    matchLabels:
      app: front-end
  replicas: 1
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
      - name: front-end
        image: __DOCKER_REPOSITORY__/__IMAGE_NAME_FE__:__IMAGE_TAG__
        ports:
        - containerPort: 22137
        resources:
          limits:
            cpu: 2800m
            memory: "4000Mi"
          requests:
            cpu: 100m
            memory: "50Mi"
        env:
          - name: back-end-service
            value: back-end-service
        #       configMapKeyRef:
        #         name: mssql-connection-configmap
        #         key: db-connection-string
        #     secretKeyRef:
        #       name: mssql-secret
        #       key: db-connection-string-secret
---
kind: Service
apiVersion: v1
metadata:
  name: front-end-service
spec:
  selector:
    app: front-end
  ports:
  - protocol: TCP
    port: 22137
    targetPort: 22137
  type: LoadBalancer #NodePort