apiVersion: apps/v1
kind: Deployment
metadata:
  name: front_end-deployment
spec:
  selector:
    matchLabels:
      app: front_end
  replicas: 1
  template:
    metadata:
      labels:
        app: front_end
    spec:
      containers:
      - name: front_end
        image: __DOCKER_REPOSITORY__/__IMAGE_NAME__:__IMAGE_TAG__
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 300m
            memory: "100Mi"
          requests:
            cpu: 100m
            memory: "50Mi"
        # env:
        #   - name: ConnectionStrings__ProductsContext
        #     valueFrom:
        #       configMapKeyRef:
        #         name: mssql-connection-configmap
        #         key: db-connection-string
        #     secretKeyRef:
        #       name: mssql-secret
        #       key: db-connection-string-secret
---
kind: Service
apiVersion: v1
metadata:
  name: front_end-service
spec:
  selector:
    app: front_end
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer #NodePort