name: Build and deploy the docker images for both back end and front end

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build-deploy-aks:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPOSITORY: aminmaliha15 # name of Docker Hub ID
      IMAGE_NAME_FE: front_end_image
      IMAGE_NAME_BE: back-end-image
      IMAGE_TAG: latest
      
      CLUSTER_NAME: ca2-project-maliha-aks
      RESOURSE_GROUP: ca2-project-maliha
    
    steps:

    - name: Git Checkout
      uses: actions/checkout@v2
  
    - name: Build Backend Docker Image
      run:
        docker build ./Back_End/ --file ./Back_End/Dockerfile --tag $DOCKER_REPOSITORY/$IMAGE_NAME_BE:latest --no-cache

    - name: Run Trivy vulnerability scanner on Backend Image
      uses: aquasecurity/trivy-action@master
      continue-on-error: true
      with:
        image-ref: 'docker.io/${{ env.DOCKER_REPOSITORY }}/${{ env.IMAGE_NAME_BE }}:${{ env.IMAGE_TAG }}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'MEDIUM,HIGH,CRITICAL'

    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_REPOSITORY_PASSWORD }}" | docker login -u $DOCKER_REPOSITORY --password-stdin
  
    - name: Push Backend Image to Docker Hub
      run:
        docker push $DOCKER_REPOSITORY/$IMAGE_NAME_BE:latest

    - name: Build Front End Docker Image
      run:
        docker build ./Front_End/ --file ./Front_End/Dockerfile --tag $DOCKER_REPOSITORY/$IMAGE_NAME_FE:latest --no-cache

    - name: Run Trivy vulnerability scanner on Front end Image
      uses: aquasecurity/trivy-action@master
      continue-on-error: true
      with:
        image-ref: 'docker.io/${{ env.DOCKER_REPOSITORY }}/${{ env.IMAGE_NAME_FE }}:${{ env.IMAGE_TAG }}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'MEDIUM,HIGH,CRITICAL'

    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_REPOSITORY_PASSWORD }}" | docker login -u $DOCKER_REPOSITORY --password-stdin
  
    - name: Push Frontend Image to Docker Hub
      run:
        docker push $DOCKER_REPOSITORY/$IMAGE_NAME_FE:latest
   
    - uses: cschleiden/replace-tokens@v1
      with:
        files: '["kubernetes/*.yaml"]'
        tokenPrefix: __ # optional, default is #{
        tokenSuffix: __ # optional, default is }#
      env:
        DOCKER_REPOSITORY: ${{ env.DOCKER_REPOSITORY }}
        IMAGE_NAME_BE: ${{ env.IMAGE_NAME_BE }}
        IMAGE_NAME_FE: ${{ env.IMAGE_NAME_FE }}
        IMAGE_TAG: ${{ env.IMAGE_TAG }}

    # Set the target AKS cluster.
    - uses: Azure/aks-set-context@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        cluster-name: ${{ env.CLUSTER_NAME }}
        resource-group: ${{ env.RESOURSE_GROUP }}

    - uses: Azure/k8s-deploy@v1
      with:
        manifests: |
          kubernetes/front-end-deployment.yaml
          kubernetes/back-end-deployment.yaml
    
    - name: Run Kube-Bench to check cluster config
      continue-on-error: true
      run: |
        kubectl apply -f https://raw.githubusercontent.com/aquasecurity/kube-bench/main/job-aks.yaml
        sleep 30s
        kubectl logs job.batch/kube-bench
        kubectl delete job.batch/kube-bench